cache:
  directories:
  - $HOME/.jdk
sudo: false
env:
  matrix:
  - EXPECTED_VERSION=1.7.0_80 JDKW_DIST=oracle JDKW_VERSION=7u80 JDKW_BUILD=b15 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_74 JDKW_DIST=oracle JDKW_VERSION=8u74 JDKW_BUILD=b02 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_144 JDKW_DIST=oracle JDKW_VERSION=8u144 JDKW_BUILD=b01 JDKW_VERBOSE=1 JDKW_TOKEN=090f390dda5b47b9b721c7dfaa008135
  - EXPECTED_VERSION=9.0.1 JDKW_DIST=oracle JDKW_VERSION=9.0.1 JDKW_BUILD=11 JDKW_VERBOSE=1
  - EXPECTED_VERSION=9.0.4 JDKW_DIST=oracle JDKW_VERSION=9.0.4 JDKW_BUILD=11 JDKW_VERBOSE=1 JDKW_TOKEN=c2514751926b4512b076cc82f959763f
  - EXPECTED_VERSION=1.7.0_161 JDKW_DIST=zulu JDKW_BUILD=7.21.0.3 JDKW_VERSION=7.0.161 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_152 JDKW_DIST=zulu JDKW_BUILD=8.25.0.1 JDKW_VERSION=8.0.152 JDKW_VERBOSE=1
  - EXPECTED_VERSION=9.0.1.3 JDKW_DIST=zulu JDKW_BUILD=9.0.1.3 JDKW_VERSION=9.0.1 JDKW_VERBOSE=1
  global:
  - secure: o8gQJM+zKtoSUiXVxs2pW3iQMZUpkWSVT8lzipPixY8L4T1ZuUorrgc2rtI8NdTdBh+A6WnCSmnOG8VtWFiSAv5ib/oBRV63sDe4xTuDYG4pRHxDjX7HT9ZxkCLXv4mucdOoUe4UUWtHBzARP4Q+nzYP1nZ9c6phT3mNybjQxBdePS54LSDf/iYnNy+LwQmceL1uyBcfsnSfWOkFoRtYdt491XAQWcsJS7Yr1dZo9MF8w9kS7SHG1iN4DADna8McV7v4FQlpQlYbGATXgmopGR9PD4+6+vSfAq5JS8jGV+hOLDvH/ioCR9u57OlcBZQNYIBqlsulF8vg/BOpva3l/083V4zkk7JlYPYsuYamkyLGYtbtHUT98VQbfqVQTIGr2w3km/lB7vLwOCQSI1gUUfPEzpGnqiDw4Zz+Blpt+JjsWOm08fxRSDSa4NuqP2LC+715LeAn+v5azcLeldVb3f5BeUVV46l1Fbi+b+qziix8zuEGyyGr7oaZym15cS4to6x9JcSeF4NsSxCndY+JySYXK0ZepSHu8ATJRsALIF2zVYPgLgFtr/l5YoOnS8FyxrCVQAeXKiV5U5m/RK9AZ8pXYCTJjD+bxhyA+X0rSnHGhlYxyzd3VWvIL5clx30V0j6hPsmVYkrg93jCh6ohNEsTq6xg//8xRvswBKv4ENw=
  - secure: LAJNMquk/R2hqvmM4TZqYO/vMMmUDMgUW8aO2gKlZk5RhCv6hNzpnu1a7WYUxM1jJav7ssI25ZYIeEo7vRZNCE0Rco0a7h9bt/Qz5YuG2bK1gwZIrxymd826gKXrG4Clhs/t8n5sJjfE/0tyZ8X/KWuglseS1jS16h7BcTSHF0e3YeJi9qkr98gBb3Sss/tmShUUtQb6NrJWrNHk3caC/kYFrtdCKwnNIh6iWmWKXjyRgM/R6lnbS5jXPmxqVwsC9ZLZc3O2PJ5haaMiA3sj7e+xLICfgvGJFjhmxRUY4CgJdmyKqx9fZaJU030JagtmZjpdz5i+Gdxac4uiTRirBxv/biB9r7pqc5Ds2PgVXscrJhpjD60uZMQYKiB/Fu97Nu82ZpvPswEkzfvb2G52kIQ1kXeqnKu1W12I/05sA9D8uQagRbJMnwU8pzs884CzmL3BbEJLMu282wZHfLxiP7OAI8JBk5imp+GQZqyFcTylpufTirOLnMKD7abNNKCuPZsOUJnSgkZqOPBUsZaVG9K4rD7lU6U5Bgjb8tXMC6nSnKVzYdb7ttgcLVYbtTv3i7dxnTo8g8Dbf48tC0yCX8kYNgDqolYofVZe9/hHkU4Py/cKcIvJfgiHEWPEPrliGG7dSoYwGYf411vzzYDF0lSIQ2T8DPXqJWDQ358l5G0=
install: true
script:
- ./jdkw-impl.sh JDKW_VERBOSE=1 JDKW_DIST=${JDKW_DIST} JDKW_VERSION=${JDKW_VERSION} JDKW_BUILD=${JDKW_BUILD} JDKW_TOKEN=${JDKW_TOKEN} javac -version
- if [ "$(./jdkw-impl.sh JDKW_VERSION=${JDKW_VERSION} JDKW_BUILD=${JDKW_BUILD} JDKW_TOKEN=${JDKW_TOKEN} javac -version 2>&1 | tail -n 1)" != "javac ${EXPECTED_VERSION}" ]; then exit 1;
  fi;
deploy:
  provider: releases
  api_key:
    secure:
  file:
  - jdk-wrapper.sh
  - jdkw-impl.sh
  on:
    repo: Koskilabs/jdk-wrapper
    tags: true