cache:
  directories:
  - $HOME/.jdk
sudo: false
env:
  matrix:
  - EXPECTED_VERSION=1.6.0_45 JDKW_DIST=oracle JDKW_VERSION=6u45 JDKW_BUILD=b06 JDKW_EXTENSION=bin JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.7.0_80 JDKW_DIST=oracle JDKW_VERSION=7u80 JDKW_BUILD=b15 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_74 JDKW_DIST=oracle JDKW_VERSION=8u74 JDKW_BUILD=b02 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_144 JDKW_DIST=oracle JDKW_VERSION=8u144 JDKW_BUILD=b01 JDKW_VERBOSE=1 JDKW_TOKEN=090f390dda5b47b9b721c7dfaa008135
  - EXPECTED_VERSION=9.0.1 JDKW_DIST=oracle JDKW_VERSION=9.0.1 JDKW_BUILD=11 JDKW_VERBOSE=1
  - EXPECTED_VERSION=9.0.4 JDKW_DIST=oracle JDKW_VERSION=9.0.4 JDKW_BUILD=11 JDKW_VERBOSE=1 JDKW_TOKEN=c2514751926b4512b076cc82f959763f
  - EXPECTED_VERSION=1.7.0_161 JDKW_DIST=zulu JDKW_BUILD=7.21.0.3 JDKW_VERSION=7.0.161 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_152 JDKW_DIST=zulu JDKW_BUILD=8.25.0.1 JDKW_VERSION=8.0.152 JDKW_VERBOSE=1
  - EXPECTED_VERSION=9.0.1.3 JDKW_DIST=zulu JDKW_BUILD=9.0.1.3 JDKW_VERSION=9.0.1 JDKW_VERBOSE=1
  global:
  - secure: IUkirtXv2zXB9BtU3zM7nkedBidlJSdgJscM1KWpObgJZllGizxyJ4x4tb4cMze21QVma0AEp7eO9FmMtfYDwDQFmm+CrZT4TzQktyYGllp/pVVL9tGs6pIytQcgE+Ik4bkMYAnL/8XeIXDAOGTmUo4y24IvN89aFVEeVYQX6Irv0dQSdf83O8yd0H9UPxRtW22rbVxPkw7cFghXe9bDQjvDgh2KwNGr3BLZxPXgTSozjS7SFYMDjkmXQVkM/xGGTLZdyJ6rui8tH3NgoP2B8ly/l3vvzJ5fYeEqlxqJYrhWrI2RVmd50Iaa+MAyM1ToGEJNRyOYY8Iwj3M4fUUolu8fY9BApAxOehzamNzq1z3TH/0jfoure+n2pTdOy99lQykfKVtWiuwvB7MQmUlls2HQsEPQCO/WqE9xOX59hH07HWbI1xUxKaxJb2UxTmG47PX+3ggSDSQAIF9R53oUM8Ae0iGtzqNmyOrCngZf3YhTWGo5KSm4RMvxZFps3Y4rUv+/psWYVZhlOLLr2zx8eGOmEfh1SYOUo+x9Ro0+kCo9yYmlAagudm9cRt2vUkjo3PiGmV1jV0aa2xxvx0Z4XJ5KOpPwtZkT1wRC6v6Yd7fAIIFTZaCevsV2JTaEtmXOGfdmeu3WOlagxxOSIjhyskodbAM1DrWKxM+AfnnK+0A=
  - secure: dJ5tf+wSsoUM0PfPywJzR92fwCAEeY3IxOpYdJlc+jYSJhh5ZBTegqIFQG+kRN5anxSW6RTclY4+Ic5OUWEbH+XueqlWGttjXZ1xvInu+mUPPYfKdYl1zsZrRVy/jaQSXpJ1ZX9cjpuLVyGd2evyb7UleW3vXw2dwgncy5R2T67aLPi/k1v3tSoIAhrNOHsnW8MBT9YQEDbuLP+PHPIH+sClYnmRUQ7Af/jhcfrqI03d+xdu8XyWed1zN/v0juUrBW9BRtpof2rlC6c2hSBhciHKqDDNvAGacOE8c3gUcxlPaC8+aRgLdRQ2VlVe15iCXbod32Wnsg/CckW8ZrgW59dyAKz+dXoV315BkwEahCQsck3lfdRBlBGRIlkJw0OkSjPemywv3POtVMdsX1KNzG27n1yZQzJ/fZWHiSXzYGjCFFBqFRqtzIM3bOS4CpqLWBrjHjDAGhdhQPFFgO6AXCcbio9ueif6x7pr+JIXp1G1PtLGtyRwywLKFVZ6hllgodTy0StmYdLmszTvI//O6sdpIrz5nUa0+Yl4T37+xi3YlNkHCByu8TedgtTbWNAB9tURFV8xgznkXOjXbEVyKKetunAXpkEyd5FQk+a0hQO7X+3StIfUmRUAItOyQ6xg8HLL/h0hT8EZD+v3ENrhUopA2Vmi4rEVI1/lzX0Mk7w=
install: true
script:
- ./jdkw-impl.sh JDKW_VERBOSE=1 JDKW_DIST=${JDKW_DIST} JDKW_VERSION=${JDKW_VERSION} JDKW_BUILD=${JDKW_BUILD} JDKW_TOKEN=${JDKW_TOKEN} javac -version
- if [ "$(./jdkw-impl.sh JDKW_DIST=${JDKW_DIST} JDKW_VERSION=${JDKW_VERSION} JDKW_BUILD=${JDKW_BUILD} JDKW_TOKEN=${JDKW_TOKEN} javac -version 2>&1 | tail -n 1)" != "javac ${EXPECTED_VERSION}" ]; then exit 1; fi;
deploy:
  provider: releases
  api_key:
    secure: pEiERgHeAC336jWEopBRt9wG5fXk2scTb7XTAxMI8LgWMqLkXbqi9mZR50vGH/0EJUNSFQorsaIiCvCkb/RW0gql0ZOX6daF3Dia6B3dLpA8pYqj0IocqlBpE0OZJoEJc7w742x9tNI6WMW/Y0ibC3PRw/XEoS4w3/fLznfTN8Wx3V/UA5zhGqdcrJ/aqAByufofQ7apWpfN1kVbWlu8abPmrJ0XP3GpgNKguG1FsDORGIwX0x3UrE0yZVCyMgbhJqJMp0ThlUwNm+AzC41WFc7B9W2petvw/H+Az/gaDaWg7DakTFXHaSD7HEt5ngLVnWtYNuJ+728LQsXheucHP3E6lagUPLeNeNKzjWlW7NA7VFHsISwHheAvmAUdecgl83/+M5kuVQr/rAm/eZ1P/XS6PvIevS10R9u+oMsOH9ciCh5okYZ5fZIVO88+nVSb5sYLlfsi4SFpbQke0k72qCd2J+6tvOlxEyGfXAqJotWvkzs1gT6ud8jVc258xAA68eByN66G8wSJvgOgU17mLZMtq4CMwnRRg2QRANrv4OEniykQ/SevsFa3EBt5J3+BgpONryFztNcYJQucVLzXPgDWM0XyFyzmaR7qfL0PjfVigPNdsQXgCdKevEztjhu+ZeEDBBDJPR9JGKwDdZmRL/U5MvMxgb7SEwrPoRqEO1I=
  file:
  - jdk-wrapper.sh
  - jdkw-impl.sh
  on:
    tags: true
    repo: KoskiLabs/jdk-wrapper
