cache:
  directories:
  - $HOME/.jdk
sudo: false
language: bash
dist: xenial
os:
  - linux
  - osx
  - windows
env:
  matrix:
  - EXPECTED_VERSION=1.7.0_161 JDKW_DIST=zulu JDKW_BUILD=7.21.0.3 JDKW_VERSION=7.0.161 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_152 JDKW_DIST=zulu JDKW_BUILD=8.25.0.1 JDKW_VERSION=8.0.152 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_212 JDKW_DIST=zulu JDKW_BUILD=8.38.0.13 JDKW_VERSION=8.0.212 JDKW_VERBOSE=1
  - EXPECTED_VERSION=9.0.1.3 JDKW_DIST=zulu JDKW_BUILD=9.0.1.3 JDKW_VERSION=9.0.1 JDKW_VERBOSE=1
  - EXPECTED_VERSION=10.0.2 JDKW_DIST=zulu JDKW_BUILD=10.3+5 JDKW_VERSION=10.0.2 JDKW_VERBOSE=1
  - EXPECTED_VERSION=11.0.3 JDKW_DIST=zulu JDKW_BUILD=11.31.11 JDKW_VERSION=11.0.3 JDKW_VERBOSE=1
  - EXPECTED_VERSION=12.0.1 JDKW_DIST=zulu JDKW_BUILD=12.2.3 JDKW_VERSION=12.0.1 JDKW_VERBOSE=1
  global:
  - secure: JgaBmGI+IOo0WlwBq1+BYK5KLI6yVaOl4S97EoR2zJwxBTk6yLfr8Gymx97bQ0miN6G3DrYGQ9bmcrDCGDEhD5uTpjt83KadjY6uPnbEmhLoowsiiLSLXh5e3rmIM9HdFywxT+9N4pKYwYwdzyIMAOre/rsocWAacf31yy8kBzWJtYqxIarrmRsCYunVdrPM14on4IBf96W6CULtbX3gdfWkUJeLo9DH9+QJ8K5v+TlnojiayZmZqSf0kSn7lb1fJOaTvySYSfginKf4VsdTjOk6kUOxurEK74ies/B9asPolxoC/V8i8/EiQxnoYTg/hilAL96Dj1Sm//tKlJ4Y5+n8eW/11V1OExeap6hPgNYUjogbBEMC3e19QBOF1x8J7GHCLxNrrRq5ECxYnc3lrmA/qaVwnGdtDl5u7Xo70FOoINlzh8wEXt1q7C1Hb7ncRUxWUMFbOyM+FDCNjWjECSjko295xSpDJR6emYpqgXr/kTqqAJW+mKFw/qOdjutoTsm9h3UoLr/dMctWgnXG/ycnBpB9eTNYsmr8wrBbb9KAN7r9Uw5V7JK93BCCfTAqb2ONaG9QmWep6YDCBL+46sOp74Z2fSwRim6fkqaEVLcruKwdoPchbapl9943RL4ptdlHmRrte/N0Jq3eKuwL8GKLuZOoM/mTJdYxvWy2i/I=
  - secure: TE9WLUtH19+KBgFyxdj9K0g7pYP4cf9YQFewUllnQwMlUyQtEzbFISC1r8cz67ALOyYI69M850R/9OPSAPI92shGFvDZIjuVsCTOB2UzpbFF4oTOKNE+mAjKebPw/bfJbpPR+QOSJ0zv8yw6stmyMk9Lh32EHyLFeRJms1F1TdOdwQas5HspQGoD/0+mdBgLSzByTtWbtCnkU0fpJCo0TYicImKum6VCpjUTwrixl6br4H0/fldaprSg3bkKysuT6ddVNMr0/VtIV6v7TbbCp3fzOnqo/E2pRlw5XyOyLsLyUYptNhg7Qi9qiUyrB+Syg+Id7VOp/RgXCH0Gj+Ya9T0Naf5km7DRh6mN2c2/9ZL//9ESrNNXzBKyeLnAKlz1TMNT8Cw0Z26riDeOa8U5UREXoj0TWe1ZU5IDTALS3M19tAiIF6JDbAnGt/dplaoaoJDz38Ez73HMOf6bw9QtH55bE516WQ9QZz3tLwW/YR6KgzRLPqRZbcd5zq58wFtSh4Q6tg/S8AsNvomyn1KCWAmInb+Gp+/SGJ5hG6diF2P/GwQ616EdX3bN1tMzeAPyUjEcpbmdewH+ZXqq7bqIc2rqn1ysE5wELmaLdNs5JDiZOzh4ma6gH9Dj3nnUADonqhK/vFA0xN1YMCKxJ5zW2FQL5bZpb8AhQNHSceR9mpU=
install: true
script:
- ./jdkw-impl.sh JDKW_VERBOSE=1 JDKW_DIST=${JDKW_DIST} JDKW_VERSION=${JDKW_VERSION} JDKW_BUILD=${JDKW_BUILD} JDKW_TOKEN=${JDKW_TOKEN} javac -version
- if [ "$(./jdkw-impl.sh JDKW_DIST=${JDKW_DIST} JDKW_VERSION=${JDKW_VERSION} JDKW_BUILD=${JDKW_BUILD} JDKW_TOKEN=${JDKW_TOKEN} javac -version 2>&1 | grep 'javac' | tail -n 1)" != "javac ${EXPECTED_VERSION}" ]; then exit 1; fi;
deploy:
  provider: releases
  api_key:
    secure: pEiERgHeAC336jWEopBRt9wG5fXk2scTb7XTAxMI8LgWMqLkXbqi9mZR50vGH/0EJUNSFQorsaIiCvCkb/RW0gql0ZOX6daF3Dia6B3dLpA8pYqj0IocqlBpE0OZJoEJc7w742x9tNI6WMW/Y0ibC3PRw/XEoS4w3/fLznfTN8Wx3V/UA5zhGqdcrJ/aqAByufofQ7apWpfN1kVbWlu8abPmrJ0XP3GpgNKguG1FsDORGIwX0x3UrE0yZVCyMgbhJqJMp0ThlUwNm+AzC41WFc7B9W2petvw/H+Az/gaDaWg7DakTFXHaSD7HEt5ngLVnWtYNuJ+728LQsXheucHP3E6lagUPLeNeNKzjWlW7NA7VFHsISwHheAvmAUdecgl83/+M5kuVQr/rAm/eZ1P/XS6PvIevS10R9u+oMsOH9ciCh5okYZ5fZIVO88+nVSb5sYLlfsi4SFpbQke0k72qCd2J+6tvOlxEyGfXAqJotWvkzs1gT6ud8jVc258xAA68eByN66G8wSJvgOgU17mLZMtq4CMwnRRg2QRANrv4OEniykQ/SevsFa3EBt5J3+BgpONryFztNcYJQucVLzXPgDWM0XyFyzmaR7qfL0PjfVigPNdsQXgCdKevEztjhu+ZeEDBBDJPR9JGKwDdZmRL/U5MvMxgb7SEwrPoRqEO1I=
  file:
  - jdk-wrapper.sh
  - jdkw-impl.sh
  on:
    tags: true
    repo: KoskiLabs/jdk-wrapper
