cache:
  directories:
  - $HOME/.jdk
sudo: false
env:
  matrix:
  - EXPECTED_VERSION=1.6.0_45 JDKW_DIST=oracle JDKW_VERSION=6u45 JDKW_BUILD=b06 JDKW_EXTENSION=bin JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.7.0_80 JDKW_DIST=oracle JDKW_VERSION=7u80 JDKW_BUILD=b15 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_74 JDKW_DIST=oracle JDKW_VERSION=8u74 JDKW_BUILD=b02 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_144 JDKW_DIST=oracle JDKW_VERSION=8u144 JDKW_BUILD=b01 JDKW_VERBOSE=1 JDKW_TOKEN=090f390dda5b47b9b721c7dfaa008135
  - EXPECTED_VERSION=9.0.1 JDKW_DIST=oracle JDKW_VERSION=9.0.1 JDKW_BUILD=11 JDKW_VERBOSE=1
  - EXPECTED_VERSION=9.0.4 JDKW_DIST=oracle JDKW_VERSION=9.0.4 JDKW_BUILD=11 JDKW_VERBOSE=1 JDKW_TOKEN=c2514751926b4512b076cc82f959763f
  - EXPECTED_VERSION=10.0.1 JDKW_DIST=oracle JDKW_VERSION=10.0.1 JDKW_BUILD=10 JDKW_VERBOSE=1 JDKW_TOKEN=fb4372174a714e6b8c52526dc134031e
  - EXPECTED_VERSION=1.7.0_161 JDKW_DIST=zulu JDKW_BUILD=7.21.0.3 JDKW_VERSION=7.0.161 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_152 JDKW_DIST=zulu JDKW_BUILD=8.25.0.1 JDKW_VERSION=8.0.152 JDKW_VERBOSE=1
  - EXPECTED_VERSION=9.0.1.3 JDKW_DIST=zulu JDKW_BUILD=9.0.1.3 JDKW_VERSION=9.0.1 JDKW_VERBOSE=1
  global:
  - secure: s8CgD2qxKeApVEbLJDPu6ufYldOBoVXFp/w2SjQowrGA7Uj25O/ayZ2uW5hK7w4WlLOJ5pp6Lj/LH0Fn4rVk8y7hBhIHgdmhB9xdGVhuAZspKqeCTccbC6VBw5vpokb0RpB7hTy+UjsbnoMBYHkMshrg6AThloovC+cCyDqWB6JjhUTWH0xTE2uYd+r4IDYoBfQ42M4HgcDRrHgdwl5PUwhiTFDQd8jx3ObtnmXdflYF5+T53cNS7zmEc1wTowOs2qh4ne3k4G6jOxnnSi/kqfejpYfFwMmBTSa4165a2FJq2g5kdgpM1vBn0vQ3/pMqphz/RInta4I6nv0yiRMCgrpyJCfyHcVU0j8COjPumE6XMjIKU8cGH+tei9uh7ZMZCPI5PIRKjy/Y4u6NrlsmnksA74HrMiKHPeb2rK0d7Mu0kXhrev3U6Kb4o8D4WTtcXZuPTU1t6OudFyj4NK/iGBWKidNAJg2jA49jCAcqb0ujVXA0R6KN3KqtVFdKGnO/rCM0JobfbOg0c1HOv8xirvJOVhYqQ6LeCcrKT+NKI+jOT50wuarFQ49OieGeEevlpj5DzATmnIizm3Dkro1X546IAfUoqw1tHTj+xKneyaPnkwkndqoYti2K+fHc5kU5GFEvoxuKAbXDfHCEZMb5nPLFHHflTh8un39Ja1ZM81Q=
  - secure: iizl1DAH6Na7YXsfGswsRmAk8cQEbztl5ObGl+npqWRktreZRYsIiFDmhjpTkw8btzXBxImThw2BiQSoQ1S9mpSeEL61Zn2cUaor6gsFD7kphZuMJmutUrcMZS+1PUOS6yWAWlkVBWAoxKxVzr3wcZvEUo5s1/tjPbXSg9WqKcXTguSTUfwJ2B3okjwaIig9ML1dNsUDQdjOvtVbnoMP90pv7wqRTwZA/7RZewNosDqx5RN417NcKF2Ay27n+SG/TdBHPuMSyeRZKmzfquK4jMkIuim8Pyq/LoNNMhCnIZkKCDd+24so+n1NusUTrq0soBrBRLLiM0RuJk/pFmtUfst7ehEsRCDO7PGlwz0a+NBq2tTPTo9y9zfJadOJv7skw9bOKQX6XTpwf+C0p7AJxFYQF+i/p7KJ7CuG8tPhnl1O3rno8FlApbm/fXtcqsGGO2hh9UuDb6GgCjHvgyUkoJ4JDwHOyC5KYa7dPYyaDDnjtXLZb5DFg2SUyeWb3rWiLd9nWRM3RWRQybpSgLlEg9OHXIUsYroilWLX3VxNlccWnrEdqZV1v60fZxL0eVfZDUpwijHuH2cnsP8Znfto/NZkBHxoEcxsGPhjqg4NDA8uXUyKJ/JXY/gIqnkTKO1O3EFls0n2cU1W5usgTtf7WPALzm59k/tQ6c1x6mgYV/8=
install: true
script:
- ./jdkw-impl.sh JDKW_VERBOSE=1 JDKW_DIST=${JDKW_DIST} JDKW_VERSION=${JDKW_VERSION} JDKW_BUILD=${JDKW_BUILD} JDKW_TOKEN=${JDKW_TOKEN} javac -version
- if [ "$(./jdkw-impl.sh JDKW_DIST=${JDKW_DIST} JDKW_VERSION=${JDKW_VERSION} JDKW_BUILD=${JDKW_BUILD} JDKW_TOKEN=${JDKW_TOKEN} javac -version 2>&1 | tail -n 1)" != "javac ${EXPECTED_VERSION}" ]; then exit 1; fi;
deploy:
  provider: releases
  api_key:
    secure: pEiERgHeAC336jWEopBRt9wG5fXk2scTb7XTAxMI8LgWMqLkXbqi9mZR50vGH/0EJUNSFQorsaIiCvCkb/RW0gql0ZOX6daF3Dia6B3dLpA8pYqj0IocqlBpE0OZJoEJc7w742x9tNI6WMW/Y0ibC3PRw/XEoS4w3/fLznfTN8Wx3V/UA5zhGqdcrJ/aqAByufofQ7apWpfN1kVbWlu8abPmrJ0XP3GpgNKguG1FsDORGIwX0x3UrE0yZVCyMgbhJqJMp0ThlUwNm+AzC41WFc7B9W2petvw/H+Az/gaDaWg7DakTFXHaSD7HEt5ngLVnWtYNuJ+728LQsXheucHP3E6lagUPLeNeNKzjWlW7NA7VFHsISwHheAvmAUdecgl83/+M5kuVQr/rAm/eZ1P/XS6PvIevS10R9u+oMsOH9ciCh5okYZ5fZIVO88+nVSb5sYLlfsi4SFpbQke0k72qCd2J+6tvOlxEyGfXAqJotWvkzs1gT6ud8jVc258xAA68eByN66G8wSJvgOgU17mLZMtq4CMwnRRg2QRANrv4OEniykQ/SevsFa3EBt5J3+BgpONryFztNcYJQucVLzXPgDWM0XyFyzmaR7qfL0PjfVigPNdsQXgCdKevEztjhu+ZeEDBBDJPR9JGKwDdZmRL/U5MvMxgb7SEwrPoRqEO1I=
  file:
  - jdk-wrapper.sh
  - jdkw-impl.sh
  on:
    tags: true
    repo: KoskiLabs/jdk-wrapper
